name: SuffixChanger
version: '${version}'
main: me.window.suffixchanger.SuffixChanger
api-version: '1.21'
depend: [LuckPerms]
authors: [Window5]
libraries:
  - net.projecttl:InventoryGUI-api:4.6.0
commands:
  suffix:
    description: Open the SuffixChanger GUI
    usage: /suffix
    permission: suffixchanger.suffix
  addsuffix:
    description: Add a group with the specified suffix to luckperms
    usage: /addsuffix <group_name> <suffix...(use as many args here as you wish)>
    permission: suffixchanger.admin
  reloadsuffixchanger:
      description: Reloads the SuffixChanger config
      usage: /reloadsuffixchanger
      aliases:
        - suffixchangerreload
      permission: suffixchanger.reload